---
- name: Ensure python-pip is installed
  apt:
    name: "{{ dehydrated_pip_package }}"
  when: dehydrated_install_pip

- name: Install dns-lexicon (pip)
  pip:
    name: dns-lexicon
    executable: "{{ dehydrated_pip_executable|default(omit) }}"
  when: not dehydrated_use_os_lexicon

- name: Install dns-lexicon (os)
  package:
    name: "{{ dehydrated_os_lexicon_package }}"
  when: dehydrated_use_os_lexicon

- name: Copy hook script
  copy:
    dest: /etc/dehydrated/hooks.d/01lexicon
    src: 01lexicon
    owner: root
    group: root
    mode: "0700"
